[build]
builder = "RAILPACK"

[deploy]
startCommand = "npm run start"
preDeployCommand = "npx prisma migrate deploy"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
